[package]
name = "rustq"
version = "0.1.0"
authors = ["Prasenjeet Dutta <prasenjeet.dutta@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-error = "1.2.2"